name: "md-snyk-gradle-jdk11"
description: "Check your Gradle application running on JDK 11 for vulnerabilties using Snyk"
author: "Michal Duda"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://snyk/snyk:gradle-jdk11"
  args:
  - snyk
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
